apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer-api-svc
  name: location-consumer-api-svc
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: location-consumer-api-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer-api-svc
  name: location-consumer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer-api-svc
  template:
    metadata:
      labels:
        service: location-consumer-api-svc
    spec:
      containers:
      - image: canberkerkmen/location-consumer-api:latest
        name: location-consumer-api-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-connection-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-connection-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-connection-configmap
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-connection-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-connection-configmap
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location-consumer-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-consumer-configmap
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always