apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer-api-svc
  name: location-producer-api-svc
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30003
  selector:
    service: location-producer-api-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer-api-svc
  name: location-producer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer-api-svc
  template:
    metadata:
      labels:
        service: location-producer-api-svc
    spec:
      containers:
      - image: canberkerkmen/location-producer-api:latest
        name: location-producer-api-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location-producer-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-producer-configmap
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always