apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-api-svc
  name: person-api-svc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: person-api-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-api-svc
  name: person-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api-svc
  template:
    metadata:
      labels:
        service: person-api-svc
    spec:
      containers:
      - image: canberkerkmen/person-api:latest
        name: person-api-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-person-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-person-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-person-configmap
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-person-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-person-configmap
              key: DB_PORT
      restartPolicy: Always
