name: Udaconnect - Package with Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push connection-api
        uses: docker/build-push-action@v3
        with:
          context: modules/connection-api
          file: modules/connection-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: canberkerkmen/connection-api:latest
      -
        name: Build and push person-api
        uses: docker/build-push-action@v3
        with:
          context: modules/person-api
          file: modules/person-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: canberkerkmen/person-api:latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: modules/frontend
          file: modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: canberkerkmen/nd064-udaconnect-app:latest
      -
        name: Build and push location-consumer-api
        uses: docker/build-push-action@v3
        with:
          context: modules/location-consumer-api
          file: modules/location-consumer-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: canberkerkmen/location-consumer-api:latest
      -
        name: Build and push location-producer-api
        uses: docker/build-push-action@v3
        with:
          context: modules/location-producer-api
          file: modules/location-producer-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: canberkerkmen/location-producer-api:latest